// Upgrade pool (PRD §13-§14). Each entry: availability condition, weight, apply().
// `ctx` = { spellState, player, stacks: Map<id, count>, wave }
export const UPGRADES = [
  // --- Spell unlock ---
  {
    id: 'unlock_lightning',
    category: 'New Spell',
    icon: '⚡',
    name: 'Unlock Lightning',
    desc: 'Learn Lightning: hold to pour a continuous beam into a demon. It aims itself, burns anything packed beside its target, and never misses — but only reaches 25 m. Press 2 to select.',
    weight: 10,
    newSpell: true,
    available: (ctx) => !ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.unlocked = true; },
  },

  // --- Fireball ---
  {
    id: 'fireball_damage',
    category: 'Fireball',
    icon: '🔥',
    name: 'Enhanced Fireball',
    desc: '+20% Fireball damage.',
    weight: 10, maxStacks: 6,
    available: () => true,
    apply: (ctx) => { ctx.spellState.fireball.damageMult *= 1.2; },
  },
  {
    id: 'fireball_radius',
    category: 'Fireball',
    icon: '💥',
    name: 'Expanded Blast',
    desc: '+25% explosion radius.',
    weight: 8, maxStacks: 4,
    available: () => true,
    apply: (ctx) => { ctx.spellState.fireball.radiusMult *= 1.25; },
  },
  {
    id: 'fireball_cost',
    category: 'Fireball',
    icon: '🔮',
    name: 'Efficient Casting',
    desc: '-20% Fireball Mana cost.',
    weight: 8, maxStacks: 3,
    available: () => true,
    apply: (ctx) => { ctx.spellState.fireball.manaCostMult *= 0.8; },
  },
  {
    id: 'fireball_speed',
    category: 'Fireball',
    icon: '☄️',
    name: 'Accelerated Fireball',
    desc: '+30% projectile speed.',
    weight: 7, maxStacks: 3,
    available: () => true,
    apply: (ctx) => { ctx.spellState.fireball.speedMult *= 1.3; },
  },
  {
    id: 'fireball_twin',
    category: 'Fireball',
    icon: '🎇',
    name: 'Twin Fireball',
    desc: 'Cast two Fireballs at once (each deals 70% damage).',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.wave >= 3,
    apply: (ctx) => { ctx.spellState.fireball.extraProjectiles += 1; },
  },
  {
    id: 'fireball_ignite',
    category: 'Fireball',
    icon: '♨️',
    name: 'Burning Touch',
    desc: 'Fireball ignites survivors: 66% of its damage burns over 3 seconds.',
    weight: 7, maxStacks: 1,
    available: (ctx) => ctx.wave >= 2,
    apply: (ctx) => { ctx.spellState.fireball.ignite = true; },
  },
  {
    id: 'fireball_detonation',
    category: 'Fireball',
    icon: '🧨',
    name: 'Demonfall Detonation',
    desc: 'Demons killed by fire explode, dealing 45% Fireball damage nearby. Chains.',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.wave >= 3,
    apply: (ctx) => { ctx.spellState.fireball.detonation = true; },
  },

  // --- Lightning (require unlock) ---
  {
    id: 'lightning_damage',
    category: 'Lightning',
    icon: '⚡',
    name: 'Enhanced Lightning',
    desc: '+25% Lightning beam damage.',
    weight: 9, maxStacks: 6,
    available: (ctx) => ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.damageMult *= 1.25; },
  },
  {
    id: 'lightning_cost',
    category: 'Lightning',
    icon: '🌀',
    name: 'Efficient Lightning',
    desc: '-20% Lightning Mana drain.',
    weight: 7, maxStacks: 3,
    available: (ctx) => ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.manaCostMult *= 0.8; },
  },
  {
    id: 'lightning_chain',
    category: 'Lightning',
    icon: '🔗',
    name: 'Chain Lightning',
    desc: 'The beam earths one demon deeper into the pack — its splash spreads to the neighbours of its neighbours (60% per extra layer).',
    weight: 8, maxStacks: 3,
    available: (ctx) => ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.extraChains += 1; },
  },
  {
    id: 'lightning_siphon',
    category: 'Lightning',
    icon: '💧',
    name: 'Static Siphon',
    desc: 'Lightning kills restore 8 Mana per demon burned down.',
    weight: 7, maxStacks: 1,
    available: (ctx) => ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.siphon = true; },
  },
  {
    id: 'lightning_battery',
    category: 'Lightning',
    icon: '🌩️',
    name: 'Arc Battery',
    desc: 'Every Lightning kill dumps the stored charge back into the beam: +35% beam damage for 2 s, refreshed by each further kill.',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.battery = true; },
  },

  // --- Frost Nova (require unlock) ---
  {
    id: 'unlock_frostnova',
    category: 'New Spell',
    icon: '❄️',
    name: 'Unlock Frost Nova',
    desc: 'Learn Frost Nova: a burst of ice around you that chills every demon it touches. Press 3 to select.',
    weight: 9,
    newSpell: true,
    available: (ctx) => ctx.wave >= 4 && !ctx.spellState.frostnova.unlocked,
    apply: (ctx) => { ctx.spellState.frostnova.unlocked = true; },
  },
  {
    id: 'frost_damage',
    category: 'Frost Nova',
    icon: '🧊',
    name: 'Enhanced Frost',
    desc: '+25% Frost Nova damage.',
    weight: 7, maxStacks: 4,
    available: (ctx) => ctx.spellState.frostnova.unlocked,
    apply: (ctx) => { ctx.spellState.frostnova.damageMult *= 1.25; },
  },
  {
    id: 'frost_radius',
    category: 'Frost Nova',
    icon: '🌨️',
    name: 'Widened Nova',
    desc: '+20% Frost Nova radius.',
    weight: 7, maxStacks: 3,
    available: (ctx) => ctx.spellState.frostnova.unlocked,
    apply: (ctx) => { ctx.spellState.frostnova.radiusMult *= 1.2; },
  },
  {
    id: 'frost_slow',
    category: 'Frost Nova',
    icon: '🥶',
    name: 'Deep Freeze',
    desc: 'Chilled demons crawl: the slow bites 30% harder.',
    weight: 6, maxStacks: 2,
    available: (ctx) => ctx.spellState.frostnova.unlocked,
    apply: (ctx) => { ctx.spellState.frostnova.slowFactorMult *= 0.7; },
  },
  {
    id: 'frost_shatter',
    category: 'Frost Nova',
    icon: '🔷',
    name: 'Shatter',
    desc: 'Chilled demons are brittle: they take +25% damage from every source.',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.spellState.frostnova.unlocked,
    apply: (ctx) => { ctx.spellState.frostnova.shatter = true; },
  },

  // --- Meteor Storm (require unlock) ---
  {
    id: 'unlock_meteor',
    category: 'New Spell',
    icon: '\u2604\uFE0F',
    name: 'Unlock Meteor Storm',
    desc: 'Learn Meteor Storm: a wide circle of falling rock around you. Costs most of the well — and can be cast on an empty one, into arcane debt. Press 5 to select.',
    weight: 8,
    newSpell: true,
    available: (ctx) => ctx.wave >= 6 && !ctx.spellState.meteor.unlocked,
    apply: (ctx) => { ctx.spellState.meteor.unlocked = true; },
  },
  {
    id: 'meteor_damage',
    category: 'Meteor Storm',
    icon: '\u{1F30B}',
    name: 'Heavier Stone',
    desc: '+25% Meteor Storm damage.',
    weight: 7, maxStacks: 4,
    available: (ctx) => ctx.spellState.meteor.unlocked,
    apply: (ctx) => { ctx.spellState.meteor.damageMult *= 1.25; },
  },
  {
    id: 'meteor_radius',
    category: 'Meteor Storm',
    icon: '\u{1F30C}',
    name: 'Widened Sky',
    desc: '+20% storm radius, and every rock lands a wider blast.',
    weight: 6, maxStacks: 3,
    available: (ctx) => ctx.spellState.meteor.unlocked,
    apply: (ctx) => { ctx.spellState.meteor.radiusMult *= 1.2; },
  },
  {
    id: 'meteor_barrage',
    category: 'Meteor Storm',
    icon: '\u{1F320}',
    name: 'Endless Barrage',
    desc: '+5 meteors per storm.',
    weight: 6, maxStacks: 2,
    available: (ctx) => ctx.spellState.meteor.unlocked,
    apply: (ctx) => { ctx.spellState.meteor.extraMeteors += 5; },
  },
  {
    id: 'meteor_overdraft',
    category: 'Meteor Storm',
    icon: '\u{1F311}',
    name: 'Arcane Overdraft',
    desc: 'An overdrawn well refills twice as fast: half the time spent in arcane debt.',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.spellState.meteor.unlocked,
    apply: (ctx) => { ctx.player.manaDebtRegenMult *= 2; },
  },

  // --- Mega Blast (require unlock) ---
  {
    id: 'unlock_megablast',
    category: 'New Spell',
    icon: '\u{1F535}',
    name: 'Unlock Mega Blast',
    desc: 'Learn Mega Blast: five seconds of gathering, then a blue sun that aims itself and takes a crowd with it. Press 6 to select.',
    weight: 8,
    newSpell: true,
    available: (ctx) => ctx.wave >= 6 && !ctx.spellState.megablast.unlocked,
    apply: (ctx) => { ctx.spellState.megablast.unlocked = true; },
  },
  {
    id: 'mega_damage',
    category: 'Mega Blast',
    icon: '\u{1F4A0}',
    name: 'Deeper Well',
    desc: '+30% Mega Blast damage.',
    weight: 7, maxStacks: 4,
    available: (ctx) => ctx.spellState.megablast.unlocked,
    apply: (ctx) => { ctx.spellState.megablast.damageMult *= 1.3; },
  },
  {
    id: 'mega_radius',
    category: 'Mega Blast',
    icon: '\u{1F30A}',
    name: 'Wider Sun',
    desc: '+20% Mega Blast radius — and the auto-aim counts the bigger crowd.',
    weight: 6, maxStacks: 3,
    available: (ctx) => ctx.spellState.megablast.unlocked,
    apply: (ctx) => { ctx.spellState.megablast.radiusMult *= 1.2; },
  },
  {
    id: 'mega_charge',
    category: 'Mega Blast',
    icon: '⏱️',
    name: 'Focused Ritual',
    desc: '-25% Mega Blast charge time. The five seconds are the real cost.',
    weight: 7, maxStacks: 3,
    available: (ctx) => ctx.spellState.megablast.unlocked,
    apply: (ctx) => { ctx.spellState.megablast.chargeTimeMult *= 0.75; },
  },

  // --- Wyrmlance (require unlock) ---
  {
    id: 'unlock_wyrmlance',
    category: 'New Spell',
    icon: '\u{1F9EC}',
    name: 'Unlock Wyrmlance',
    desc: 'Learn Wyrmlance: throw a heavy pair of emerald serpents that braid around each other as they fly. They drill through every demon on a dead-straight line without weakening, and they reach no wider than the braid itself. A demon your line runs through takes both fangs; one you only brush takes a third of that; one standing beside it takes nothing at all. Press 7 to select.',
    weight: 9,
    newSpell: true,
    available: (ctx) => ctx.wave >= 5 && !ctx.spellState.wyrmlance.unlocked,
    apply: (ctx) => { ctx.spellState.wyrmlance.unlocked = true; },
  },
  {
    id: 'lance_damage',
    category: 'Wyrmlance',
    icon: '\u{1F9B7}',
    name: "Serpent's Bite",
    desc: '+25% Wyrmlance damage, both fangs and the graze alike \u2014 and the braid burns brighter and thicker for it.',
    weight: 7, maxStacks: 5,
    available: (ctx) => ctx.spellState.wyrmlance.unlocked,
    apply: (ctx) => { ctx.spellState.wyrmlance.damageMult *= 1.25; },
  },
  {
    id: 'lance_girth',
    category: 'Wyrmlance',
    icon: '\u{1F300}',
    name: 'Widening Coil',
    desc: '+18% coil width. The serpents swing wider and the full-damage stream widens with them \u2014 shots that used to only graze now take both fangs. It never reaches one finger further sideways than it already did.',
    weight: 6, maxStacks: 2,
    available: (ctx) => ctx.spellState.wyrmlance.unlocked,
    apply: (ctx) => { ctx.spellState.wyrmlance.radiusMult *= 1.18; },
  },
  {
    id: 'lance_speed',
    category: 'Wyrmlance',
    icon: '\u{1F3F9}',
    name: 'Rifling',
    desc: '+30% launch speed. The pair crosses the hall before a demon can step out of it, and you lead your shots half as far.',
    weight: 6, maxStacks: 2,
    available: (ctx) => ctx.spellState.wyrmlance.unlocked,
    apply: (ctx) => { ctx.spellState.wyrmlance.speedMult *= 1.3; },
  },
  {
    id: 'lance_cost',
    category: 'Wyrmlance',
    icon: '\u{1F48E}',
    name: 'Ophidian Thrift',
    desc: '-20% Wyrmlance mana. A full well throws seven braids instead of five.',
    weight: 6, maxStacks: 3,
    available: (ctx) => ctx.spellState.wyrmlance.unlocked,
    apply: (ctx) => { ctx.spellState.wyrmlance.manaCostMult *= 0.8; },
  },
  {
    id: 'lance_strand',
    category: 'Wyrmlance',
    icon: '\u{1F40D}',
    name: 'Third Serpent',
    desc: 'A third head winds into the braid. Each fang bites for 78% \u2014 but three of them land where two did: +17% on anything your line runs through.',
    weight: 4, maxStacks: 1,
    available: (ctx) => ctx.spellState.wyrmlance.unlocked && ctx.wave >= 8,
    apply: (ctx) => { ctx.spellState.wyrmlance.extraProjectiles += 1; },
  },

  // --- Movement ---
  {
    id: 'dash_cooldown',
    category: 'Movement',
    icon: '💨',
    name: 'Swift Step',
    desc: '-15% Dash cooldown.',
    weight: 6, maxStacks: 4,
    available: () => true,
    apply: (ctx) => { ctx.player.dashCooldownMult *= 0.85; },
  },
  {
    id: 'dash_tempest',
    category: 'Movement',
    icon: '🌪️',
    name: 'Tempest Step',
    desc: 'Dashing discharges a static nova: 20 Lightning damage to nearby demons (scales with Lightning damage upgrades).',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.spellState.lightning.unlocked,
    apply: (ctx) => { ctx.spellState.lightning.tempest = true; },
  },

  // --- Vitality / Mana ---
  {
    id: 'max_hp',
    category: 'Vitality',
    icon: '❤️',
    name: 'Demonhide Ward',
    desc: '+20 Maximum Health, and heal 20 HP.',
    weight: 6, maxStacks: 5,
    available: () => true,
    apply: (ctx) => { ctx.player.maxHP += 20; ctx.player.heal(20); },
  },
  {
    id: 'max_mana',
    category: 'Arcane',
    icon: '💠',
    name: 'Deepened Well',
    desc: '+20 Maximum Mana, and restore 20 Mana.',
    weight: 6, maxStacks: 5,
    available: () => true,
    apply: (ctx) => { ctx.player.maxMana += 20; ctx.player.addMana(20); },
  },
  {
    id: 'essence_overflow',
    category: 'Arcane',
    icon: '💎',
    name: 'Essence Overflow',
    desc: 'Mana Essence collected while your Mana is full heals 5 HP.',
    weight: 6, maxStacks: 1,
    available: (ctx) => ctx.wave >= 2,
    apply: (ctx) => { ctx.player.essenceOverflow = true; },
  },
];

export const UPGRADE_RULES = {
  optionsPerScreen: 3,
  // While Lightning is locked, force it into the offered options (PRD: unlockable
  // during early progression — guarantee the player meets the unlock system early).
  forceLightningOfferWhileLocked: true,
};
